### ISSUE TITLE
Express: Front-End Controller

### ISSUE THREAD

**Issue by khygge** [blaubachs/wild-thorn-apothecary#26]
Need to create routes inside of /controllers that are imported into index.js.

These routes will be responsible for sending data to their respective templates in handlebars. Reference Chirpy for examples in frontEndController.js.

This issue will be updated and split into multiple as the project progresses.

**Comment by VisualViolet** [comment]
Basic routes to templates completed.

**Comment by VisualViolet** [comment]
This should be done if not almost done.
